name: Black Duck (Rapid)

# Run Rapid Scan on all pull requests and pushes to a main branch
on:
  # Run Black Duck on pushes to main branches, and pull requests that are going
  # to be merged to main branches.
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

  # Allow ad-hoc, manual invocations of the Coverity workflow.
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on - Black Duck can also run on Windows and macOS
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up JDK 11 in runtime environment, necessary for running the Detect tool (invoked by the
      # detect plugin)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Black Duck (Rapid scan)
        uses: synopsys-sig/detect-action@v0.3.0
        # You can use this option to configure a CA cert if using a self-hosted runner and self-signed
        # certificates on your Hub server. This option should point to a file on the local filesystem
        # with the CA chain cert
        #env:
        #  NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
        with:
            scan-mode: RAPID
            github-token: ${{ secrets.GITHUB_TOKEN }}
            detect-version: 7.12.0
            blackduck-url: ${{ secrets.BLACKDUCK_URL }}
            blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
